export const ACTIVATE_FILE_CHANGED = 'activateFileChanged'
export const EDITOR_CHANGED = 'editorChanged'
export const FILE_ADDED_LINE = 'fileAddedLine'
export const FILE_CREATED = 'fileCreated'
export const FILE_EDITED = 'fileEdited'
export const FILE_REMOVED = 'fileRemoved'
export const FILE_SAVED = 'fileSaved'
